module.exports = {
    ENUM: {
        HTTP_CODES: {
            BAD_REQUEST: 400,
            DUPLICATE_VALUE: 409,
            FORBIDDEN: 403,
            INTERNAL_SERVER_ERROR: 500,
            METHOD_NOT_ALLOWED: 405,
            MOVED_PERMANENTLY: 301,
            NOT_ACCEPTABLE: 406,
            NOT_FOUND: 404,
            NO_CONTENT_FOUND: 204,
            OK: 200,
            PERMANENT_REDIRECT: 308,
            UNAUTHORIZED: 401,
            UPGRADE_REQUIRED: 426,
            VALIDATION_ERROR: 422,
            MULTIPLE_LOGIN: 409,
            NOT_FOUND_FOR_FIRM: 407,
        },
    },
    MESSAGE: {
        TOKEN_REQUIRED: 'Token required.',
        INVALID_TOKEN: 'Invalid token.',
        UNAUTHORIZED: 'Unauthorized.',
        LOGIN: "User Logged in Successfully",
        LOGOUT: 'Logout successfully.',
        INTERNAL_SERVER_ERROR: 'Internal server error.',
        DUPLICATE_KEY: 'Duplicate key.',
        TOKEN_ALREADY_USED: 'Token already used.',
        INVALID_ROUTE: "Oops! Looks like you're lost.",
        SUCCESS: 'Success.',
        FAILED: 'Failed.',
        NOT_FOUND: 'Not found.',
        INVALID_PASSWORD: 'Invalid password.',
        EMAIL_NOT_FOUND: 'Email not found.',
        ALREADY_EXISTS: 'Already exists.',
        DUPLICATE_ENTRY: 'Duplicate entry.',
        USER_CREATED: "User Registered sucessfully."
    },
};